hughsie/colord

configure.ac
Otherwise the build will fail when sane is enabled and the examples are
disabled.
=> Check for dbus when enabling sane

contrib/session-helper/cd-main.c
We don't want to free the thing we're trying to return. This fixes the
bug introduced in commit b6f7c4d117a06f059a6e852e2dce8c13a3bb1f2c.
See:
https://bugzilla.redhat.com/show_bug.cgi?id=1190720
=> Fix session-helper failing to find argyll tool.

lib/colord/cd-context-lcms.c
I was working on fixing leaks in darktable, and found this.
I have installed colord with this change into /usr/local, and verified that this fixes the LeakSanitizer
complaint, makes *darktable-cmstest* leak-free and does not seem to cause any side-effects (at least so far).
We have manually allocated it in cd_context_lcms_new(), and
g_clear_error() does not free it, only it's content, if any.
Fixes following LeakSanitizer-detected leak:
Direct leak of 8 byte(s) in 1 object(s) allocated from:
0 0x7f98f9924895 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x54895)
1 0x7f98f93af7f1 in g_malloc0 (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x4f7f1)
2 0x7f98f8306d19 in cd_context_lcms_new /home/lebedevri/src/colord/lib/colord/cd-context-lcms.c:154
3 0x7f98f8314dd8 in cd_icc_init …
=> cd_context_lcms_free(): do not leak GError**

lib/colord/cd-client.c
I was working on fixing leaks in darktable, and found this.
I have installed colord with this change into /usr/local, and verified that this fixes the LeakSanitizer complaint, makes darktable free of leaks in colord (or, at least i was not able to trigger others...) and does not seem to cause any side-effects (at least so far).
The reason is: client->priv is re-used several times, and cd_client_finalize()
is called only once at the end, so if cd_client_connect_cb() is called more
than once, it will re-duplicate those 3 strings, and the memory allocated
previously will leak.
Fixes several following LeakSanitizer-detected leaks like:
```
Direct leak of 23 byte(s) in 1 object(s) allocated from:
0 0x7f647ff0474f in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x5474f)
1 0x7f647d29f799 in …
```
=> cd_client_connect_cb(): do not leak strings

configure.ac
Systemd 209 merged all the sundry libsystemd-* libraries into a single libsystemd
library. Update the systemd-login check to first test for libsystemd, then
libsystemd-login if the first check fails.
=> Check for, and prefer, libsystemd over libsystemd-login.

contrib/session-helper/cd-main.c
I have a Samsung SyncMaster SA300 monitor; the model is referred as "Samsung SA300/SA350", which causes session-helper to set the basename to "Samsung SA300/SA350 (high) 2016-03-19 23-18-37 colorhug2", which of course fails because of the '/' in the filename.
=> session-helper: Replace '/' with '-' on the basename so creating the profile file doesn't fail.

src/sensors/cd-sensor-argyll.c
There was a 10s timeout for spotread to finish sampling.  This works
fine for light colors, in which case it may finish in as little as 3
seconds.  But the darker the color is, the longer it takes to finish.
When measuring black, it takes around 25-30 seconds for my Spyder 3
Express.
The timeout caused Gnome Control Panel to fail when attempting to
calibrate.
=> Increase timeout to 60s for argyll spotread sampling

configure.ac, src/cd-common.c
We cannot check on the internal name created by G_DECLARE_AUTO* macros
because it's not a pre-processor symbol.
Instead, we should check whether we're being built against a version of
PolKit that has those symbols, and only define them ourselves for
previous versions.
This commit fixes a build failure in GNOME Continuous.
=> Check polkit version before defining g_autoptr macros

configure
GNOME Continuous is passing more options to the build-api wrapper.
=> Add more options to the build-api compat script

data/profiles/its/colord.its
It was translatable before the move to gettext/Meson.
=> its: Make copyright translatable

src/meson.build
If we don't add the generated resource files as a source dependency,
Meson won't know that it has to build them first; this means that in
some cases, parallel builds will fail.
=> build: cd-self-test depends on generated resources

configure, meson.build, meson_options.txt
Build services like GNOME Continuous avoid building documentation, in order to skip the dependencies on docbook and other tools.
=> Conditional docs

lib/colorhug/meson.build
When generating the ch-version.h header, we need to replace a set of
symbols at configuration time. The configuration_data object we are
using does not contain them.
Meson warns about this in newer versions:
WARNING: The variable(s) 'CD_MAJOR_VERSION', 'CD_MICRO_VERSION',
'CD_MINOR_VERSION' in the input file 'lib/colorhug/ch-version.h.in'
are not present in the given configuration data
And the generated header is also invalid.
=> Replace the correct symbols in ch-version.h

meson.build
We use C99 features (cd-spectrum.c:760), so need to explicitly enable them
in meson.build, as some compilers will not enable them automatically,
and will instead error when they encounter usage of C99.
Signed-off-by: Philip Withnall <withnall@endlessm.com>
=> build: Enable C99 support in meson.build

meson.build
We need realpath() (and PATH_MAX) for the tests, both of which need the
_XOPEN_SOURCE feature test macro. Define it.
Signed-off-by: Philip Withnall <withnall@endlessm.com>
=> build: Define _XOPEN_SOURCE in order to expose realpath() in headers

lib/colord/meson.build
This prevents the parsing of Gio-2.0.gir, which would require additional
metadata to succeed.
Fixes #54
=> colord: pass --pkg gio-2.0 when generating VAPI

lib/colord/cd-test-shared.c
Colord fails to build in GNOME Continuous without these changes.
See full build log: http://build.gnome.org/continuous/buildmaster/builds/2017/08/12/18/build/log-colord.txt
=> Build fixes

po/meson.build
Translation files in Transifex are lacking the color profile descriptions. It *could* be because of missing data_dirs in po/meson.build.
=> build: Add data_dirs to po/meson.build

meson.build
If I'm not mistaken the message is out of date.
=> Update warning about running daemon as root

contrib/ci/Dockerfile-fedora, meson.build
Meson 0.46.0 adds `has_link_argument` to compiler objects, and we should use it instead of `has_argument` when checking linker arguments.
Fixes: https://github.com/hughsie/colord/issues/69
=> build: Fix linker argument checks

meson.build
Since we now require meson 0.46, we can use this function
that was added in 0.44.
=> Change our message to use the warning function

meson.build, src/sensors/argyll/cd-sensor-argyll.c
Previously with autotools I could manually override the `SPOTREAD` variable in package build to force it to be found. There doesn't seem to be an equivalent thing for meson, so spit out a warning if spotread is not found but allow the build to proceed.
Also it seems that cd-sensor-argyll sometimes spawns `spotread` and sometimes spawns `/usr/bin/spotread`; since the meson check is for `spotread` in `$PATH`, consistently use non-absolute paths.
=> Tweaks to cd-sensor-argyll

lib/colord/meson.build, lib/colorhug/meson.build
Allows compilation when cross building, as Void Linux is doing so.
Other packages that also do it:
libgusb -> -DGUSB_COMPILATION
atk -> -DATK_COMPILATION
appstream-glib -> -DAS_COMPILATION
=> lib/colord/meson.build: pass -DCD_COMPILATION to gir compiler

data/colord.conf, data/colord.conf.in, data/meson.build
On Endless, we previously configured colord to run as root, because otherwise it was not able to create /var/lib/colord. In the intervening years, a tmpfiles.d snippet was added to create that directory structure, so I now want to configure colord to run as colord.
However, on existing systems, files in the state directory are root-owned, so if I just configure it to run as colord it will be unable to write to its state files:
colord[668]: CdDevice: failed to save mapping to database: SQL error: attempt to write a readonly database
It is a 1-line change to the tmpfiles.d file to make it fix permissions on existing files. To quote the commit message:
> 'd' creates a directory if missing, and fixes its permissions if it already
> exists, but it is not recursive. 'Z' recursively adjusts the …
=> Fix owner & permissions on existing state files using tmpfiles.d snippet

src/cd-main.c
These functions can return a positive integer on success. Fix the conditions to only regard negative return values as errors.
Fixes commit 6ffe2f6aae4bdc8331cab1fd9379ed8aef759749.
=> trivial: Fix error checking for sd_pid_get_session and sd_session_get_seat

src/sensors/dummy/cd-sensor-dummy.c
`g_autoptr(GTask) task` will be unreffed when it leaves scope. If we want
it to be available in 2 seconds' time in the idle callback we'll need to
explicitly transfer ownership.
=> tests: Fix cd-sensor-dummy

src/cd-main.c
This is a follow up from https://github.com/hughsie/colord/commit/513bfa4783d0a630c226ee40638ab346c0d1c229 with a goal to avoid unnecessary spam in system logs. 
Fixes https://github.com/hughsie/colord/issues/48
=> trivial: Downgrade more trivial warning to a debug statement

lib/colord/cd-icc-utils.c, lib/colord/cd-icc-utils.h, lib/colord/cd-icc.c, lib/colord/cd-icc.h, lib/colord/cd-it8-utils.c, lib/colord/cd-math.c, lib/colord/cd-math.h
Modern computer display hardware supports having a 3x3 (or 3x4, in some cases) color transformation matrix between the degamma and regamma lookup tables. Currently, these matrices are not used by desktop environments and instead, the desktop environment chooses a single ICC profile to present to applications, and some applications use that to apply their own correction matrix.
Downsides to this approach are that only the profile for a single "primary" monitor is available to applications, and only some color-aware applications actually make use of these profiles. Using the hardware matrix allows the appropriate correction to be applied on a per-monitor basis, and for it to be applied automatically by the window system rather than requiring per-application support.
In order to use this …
=> libcolord: Add helpers for computing color adaptation matrices

lib/colord/cd-icc.c
`data` is an array, but without the correct annotation it is treated as a single (binary data) value by GObject introspection.
With this fix, e.g. Python code like this works:
```
icc_data = icc.save_data(Colord.IccSaveFlags.NONE)
icc2 = Colord.Icc()
icc2.load_data(icc_data.get_data(), Colord.IccLoadFlags.FALLBACK_MD5)
```
(Yes, that code is a workaround in itself... :wink:)
Thanks to Chris Williams from the GNOME `#python` IRC channel for pointing out the annotations being wrong.
=> fix cd_icc_load_data() annotation for the data array

lib/colord/cd-test-private.c, meson.build
On some platforms (at least i386, armel, and s390x) the `cd_icc_get_version` tests fail, as the floating point values are not *exactly* equivalent.
=> tests: Don't use exact floating point comparisons.

lib/colord/cd-icc-utils.c, lib/colord/cd-icc-utils.h, lib/colord/cd-icc.c, lib/colord/cd-icc.h
I forgot to add copyright notices for commits 9aba3df and 6d64e4c.
=> libcolord: Add missing copyright notices

src/cd-device-db.c
This PR fixes the issue https://github.com/hughsie/colord/issues/110 by setting the 5th parameter of `sqlite3_exec()` to NULL.
=> Fix the potential memory leak of sqlite3_exec()

lib/colord/cd-client.c
It's just a little copy/paste error, but it made me do a double-take.
=> Fix typo in device-removed signal documentation

contrib/session-helper/org.freedesktop.ColorHelper.gschema.xml, doc/website/faq.html
The domain has been abandoned and taken over by spammers.
Color profile upload was never implemented in colord.
The ColorHug family of products is no longer produced:
https://blogs.gnome.org/hughsie/2018/02/01/no-new-batches-of-colorhug2/
=> Drop references to hughski.com

lib/colord/cd-context-lcms.c
lcms 2.14 contains a change to avoid a memory leak, but that change assumes correct API usage. It's not necessary to both cmsUnregisterPluginsTHR() and then cmsDeleteContext() -- we can just straight up delete the LCMS context instead (cmsDeleteContext()).
So, follow upstream's suggestion & do that. This fixes memory corruption when building colord on x86, for example.
Bug: https://github.com/mm2/Little-CMS/issues/344
Fixes: https://github.com/hughsie/colord/issues/145
Signed-off-by: Sam James <sam@gentoo.org>
=> lib: avoid destructing LCMS plugin twice with lcms 2.14

lib/colord/cd-icc.c
cd_icc_load() always takes ownership of the passed profile, but will leak it if the initial condition fails and the funtion returns an error. Only if the actual profile loading fails, will the passed profile eventually not be leaked. Fix this by closing it immediately in the first case.
----
This might not be a good solution, but the API doesn't allow  the caller to close the profile after calling the load function, so we need something to not leak here. The alternative is to *always* set the internal pointer to have it closed on finalization; that would avoid any user-after-free if the caller makes the assumption that the profiles is still valid (which might not be that far fetched since the API mentions it's kept around until finalize).
Another alternative is to treat it as a …
=> lib/icc: Always close profile when loading fails

doc/website/faq.html
The domain has been abandoned but the code is archived on GitHub.
See-also: https://github.com/hughsie/colord/issues/134
See-also: https://github.com/hughsie/colord/pull/135
=> Update link to colorhug-client

data/colord.conf.in
Specifying the 0755 mode for the 'Z' directive applies not only to directories but also to files, making them executable. Instead, omit the mode so that directories and files are given the default 0755 and 0644 modes, respectively.
Fixes: rhbz#2249302
=> data: don't make state files executable in tmpfiles.d/colord.conf

meson.build
We call `gmtime_r` (which expects `time_t`) with a 64-bit pointer (`gint64*`).
On 32-bit systems, `time_t` is 32-bit unless you opt-in to a 64-bit wide version (at least on glibc). To avoid truncation and -Wincompatible-pointer-types, opt-in to 64-bit `time_t` for glibc with `-D_TIME_BITS=64` in meson.
This should be fine ABI wise because the time is only passed down into lcms2 into `_cmsEncodeDateTimeNumber` where it seems to decompose it and it worked already for 64-bit systems. Plus, they use their own types like `cmsUInt16Number` to ensure they're wide enough.
Fixes: https://github.com/hughsie/colord/issues/157
=> meson.build: use 64-bit time_t

meson.build
This is needed if building introspection because:
a) Meson's own setting of FILE_OFFSET_BITS (which it does by default) doesn't affect the introspection tooling;
b) glibc's headers seem to react poorly to _just_ _TIME_BITS being set, even though in this cas, the failure was for a 64-bit ABI anyway.
This is effectively a noop given meson always sets -D_FILE_OFFSET_BITS=64, it just didn't get propagated to the right bit, and we didn't notice until the change in ce9732a87bc2a0ddca841b49b9b9e24351ea78c8.
Fixes: ce9732a87bc2a0ddca841b49b9b9e24351ea78c8
=> meson.build: set FILE_OFFSET_BITS explicitly

lib/colord/cd-icc-utils.c
When making a proofing transform, we place it in it's own context. Then when setting an alarm code later, we should use the same context to ensure our intended alarm code is set in the right context.
=> Use thread context for Gamut Alarm codes.

src/cd-device-db.c, src/cd-mapping-db.c, src/cd-profile-db.c
when an error does not happen, and an error_msg pointer is passed,
sqlite does not touch it. that means this pointer is uninitialised
(=NULL) which violates the constraints of g_autofree ("the variable must
be initialized").
this is then passed to g_free and crashes in tests.
use a regular pointer and free it manually on error, after sqlite writes
to it after setting it with sqlite_malloc.
fixes https://github.com/hughsie/colord/issues/163  
---
of note `cd_profile_db_empty` and every other place with sqlite error handling was already doing this
=> fix NULL passed to free with sqlite3 error_msg pointers

src/cd-common.h, src/cd-device-db.c, src/cd-mapping-db.c, src/cd-profile-db.c
my prior analysis was completely wrong, and the original crash was seen because sqlite3_malloc pointers passed to g_free cause a mismatched malloc/free, not because of lack of initialisation.
use autoptr with an overriden CLEANUP_FUNC instead. for cd_mapping_db_load/cd_device_db_remove, keep using manual sqlite3_free since we reuse the same error_msg multiple times.
---
thanks to @jtojnar for noticing my fuckup :) could you have another look?
=> use g_autoptr again but with a custom CLEANUP_FUNC

man/cd-create-profile.xml, man/cd-fix-profile.xml, man/cd-it8.xml, man/colormgr.xml
Without it, the man page contains "FIXME: source" at the left-bottom corner.
=> man: Add the source attribute for each man page

meson.build, org.freedesktop.colord.metainfo.xml
This allow isenkram to propose this package the right hardware is present.
The provides list was generated using
for m in $(grep ATT rules/69-cd-sensors.rules.in|cut -d\" -f2,4 | \
tr a-z A-Z|tr \" p); do echo "<modalias>usb:v${m}d*</modalias>"
done
This issue started in https://bugs.debian.org/1077046 .
=> Added AppStream metainfo XML with hardware provide info.

org.freedesktop.colord.metainfo.xml
I just discovered that the AppStream parser in Debian find an error in the AppStream metadata XML I introduced in commit 259f5cbf28e917841a888af219b5fbfd1a7692ad.  Due to a cut-n-paste error on my part, the component uses type="desktop", which should only be used by packages with a XDG .desktop file.
=> Drop component type from AppStream metadata XML to avoid parsing error.
